### ISSUE TITLE
Multiple fields of the same type in a block

### ISSUE THREAD

**Issue by cdarken** [novius/novius_blocks#9]
How can I do what the title says?

**Comment by jiboule** [comment]
If I understand well, you want to add a new field to a block (eg: a sub-title or whatever) and you don't know how, is that it ?

If so, although I didn't worked with Novius OS in a while, I'd guess that you should do the following :

Let's say you want to add a subtitle for an exemple
- You have to create a migration for your database and add the new field in the novius_blocks table
- Extend the blocks crud configuration and add your field into it (in the layout and in the fields)
- Specify that you use this field in the wanted blocks (in local/config/apps/novius_blocks/templates.config.php  for example, add your new field in the "fields" key)

I think this sould do it !

**Comment by cdarken** [comment]
I was thinking more like a repeater for an existing field type, like link.

**Comment by jiboule** [comment]
there is no way (imo) to repeat fields on the fly in this context (I mean this fonctionnality is not implemented here).
What you would have to do is adding every field you want in addition in the db, the config files and your block configuration.
But again, maybe someone who's currently into Nos could prove me wrong !

**Comment by shaoshiva** [comment]
Hi !

Maybe you can achieve that by using the "Hasmany" renderer (https://github.com/novius/novius_renderers/). There are some instructions on how to use it in the "novius_docs/hasmany/" folder.
